#!/bin/bash
find . -empty | rev | cut -d '/' -f 1 | rev#!/bin/bash
find . -empty | rev | cut -d '/' -f 1 | rev#!/bin/bash
find . -empty | rev | cut -d '/' -f 1 | rev#!/bin/bash
find . -empty | rev | cut -d '/' -f 1 | rev#!/bin/bash
find . -empty | rev | cut -d '/' -f 1 | rev#!/bin/bash
find . -empty | rev | cut -d '/' -f 1 | rev#!/bin/bash
find . -empty | rev | cut -d '/' -f 1 | rev
